spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=FALSE
    url: jdbc:h2:tcp://localhost/~/jpashop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true    system.out으로 보이는 것
        format_sql: true
        default_batch_fetch_size: 1000
        # 100~ 1000 사이 가능 // 1000으로 하는게 성능상 가장 좋다.


logging:
  level:
    org.hibernate.SQL: debug
   # org.hibernate.type: trace

